[package]
name = "dusk-pki"
version = "0.5.2"
authors = ["zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network>"]
edition = "2018"

[dependencies]
rand_core = "0.5"
dusk-bytes = "0.1"
subtle = "^2.2.1"
dusk-jubjub = {version="0.8", default-features=false}
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", tag = "v0.17.0", default-features = false}
canonical = {version = "0.5", optional = true}
canonical_derive = {version = "0.5", optional = true}

[dev-dependencies]
rand ="0.7"
sha2 = "0.8"

[features]
canon = [
    "canonical",
    "canonical_derive",
    "dusk-jubjub/canon"
]
