[package]
name = "dusk-pki"
version = "0.6.0"
authors = ["zer0 <matteo@dusk.network>", "Victor Lopez <victor@dusk.network"]
edition = "2018"

[dependencies]
rand_core = "0.5"
dusk-jubjub = "0.8"
poseidon252 = {git = "https://github.com/dusk-network/Poseidon252", tag = "v0.17.0", default-features = false}
subtle = "^2.2.1"
canonical = {version = "0.5", optional = true}
canonical_derive = {version = "0.5", optional = true}
dusk-bytes = { version = "0.1" }

[dev-dependencies]
rand ="0.7"
sha2 = "0.8"

[features]
canon = [
    "canonical",
    "canonical_derive",
    "dusk-jubjub/canon"
]
